# postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec: 
      containers:
        - name: postgres
          image: postgres:15
          ports:  
            - containerPort: 5432
          env:  
            - name: POSTGRES_DB
              value: hive
            - name: POSTGRES_USER
              value: hive_user
            - name: POSTGRES_PASSWORD
              value: hive_password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data # Default PG data path
            - name: postgres-logs
              mountPath: /var/log/postgresql      # Custom logs path
       
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgres-logs
          emptyDir: {}  # Logs ca be ephemeral or persisted seperatly 