FROM fedora:40

# Set working directory
WORKDIR /app

# Insttall Python

RUN dnf install -y python3 python3-pip \
    && dnf clean all

RUN dnf install -y \
    procps-ng \
    iproute \
    net-tools \
    util-linux \
    && dnf clean all
